- name: Set up Cloud SDK
  uses: DVanyan/Googleproject@main
    with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      export_default_credentials: true