name: Pull Request
on:
  pull_request

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terratest
        uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test/src
