name: "Test vpc creatin on Google Cloud"

env:
  GOOGLE_CD: ${{ secrets.GCP_SECRET }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    env:
      GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CD }}
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
