name: "Test vpc creatin on Google Cloud"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      google_credentials: ${{ secret.GCP_SA_KEY}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
