name: "Test vpc creatin on Google Cloud"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        env: 
          credentials: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        id: init
        run: terraform init
        env: 
          credentials: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env: 
          credentials: '${{ secrets.GCP_SA_KEY }}'
